### ISSUE TITLE
Module content in 1.0.8 has not changed since 1.0.7

### ISSUE THREAD

**Issue by yoshiki-maruya** [pamelafox/ndjson-readablestream#4]
Hi Pamela.
Thanks for getting my pull request the other day.
You upgraded the version to 1.0.8 at that time, but looking at the contents, it seems that the module is still out of date.
Please check it out.

<img width="475" alt="スクリーンショット 2023-11-30 20 27 25" src="https://github.com/pamelafox/ndjson-readablestream/assets/120103911/8ce13d40-3525-4581-8df0-640d32dc0d4f">

**Comment by pamelafox** [comment]
Ah, I missed the build step, my apologies. Can you try 1.0.9?

**Comment by yoshiki-maruya** [comment]
Thank you very much.
The problem has been resolved in 1.0.9.

<img width="468" alt="スクリーンショット 2023-12-01 0 02 11" src="https://github.com/pamelafox/ndjson-readablestream/assets/120103911/61ca6c12-42eb-4b98-8dfb-0ff4c0fce282">

**Comment by pamelafox** [comment]
great thanks!
