### ISSUE TITLE
While trying to import it in a React application, it's throwing module doesn't export anything. 

### ISSUE THREAD

**Issue by yashika18** [pamelafox/ndjson-readablestream#6]

**Comment by pamelafox** [comment]
Do you have an example? We import into a React app successfully here:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/294bc3aa74d04fc24b1ec6459052c2cae2a017af/app/frontend/src/pages/chat/Chat.tsx#L4

With this package.json:

https://github.com/Azure-Samples/azure-search-openai-demo/blob/294bc3aa74d04fc24b1ec6459052c2cae2a017af/app/frontend/package.json

**Comment by pamelafox** [comment]
Closing due to no response/example.
